const $=(id)=>document.getElementById(id);const state={overview:null,selected:'src_orders',checks:[]};
const toast=(msg)=>{const n=$('toast');n.textContent=msg;n.classList.add('show');setTimeout(()=>n.classList.remove('show'),4600)};
async function api(path,opts){const r=await fetch(path,opts);const data=await r.json();if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:'Request failed');return data}
const post=(path,body={})=>api(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
const pill=(value)=>{const color=value==='FAILING'||value==='FAIL'?'fail':value==='IMPACTED'?'warn':'green';return `<span class="tag ${color}">${value}</span>`};
async function refresh(){try{const [s,c,history]=await Promise.all([api('/api/overview'),api('/api/checks'),api('/api/incidents')]);state.overview=s;state.checks=c.checks;renderSummary(s);renderNodes(s.nodes);renderChecks();renderHistory(history);inspect(state.selected)}catch(e){toast(e.message)}}
function renderSummary(s){const m=s.summary;$('healthScore').textContent=m.reliability_pct+'%';$('healthScore').classList.toggle('positive',m.failing===0);$('incidentCount').textContent=m.open_incidents;$('impactCount').textContent=m.impacted;$('healthyCount').textContent=m.healthy}
function renderNodes(nodes){const columns=[['src_orders','src_payments','src_inventory'],['stg_orders','stg_payments'],['fact_sales','fact_stock'],['dash_revenue','dash_ops']];$('nodeBoard').innerHTML=columns.map((col,i)=>`<div style="display:flex;flex-direction:column;gap:10px"><div class="metric-label" style="margin-bottom:4px">${['01 / SOURCES','02 / STAGING','03 / MODELS','04 / CONSUMERS'][i]}</div>${col.map(id=>{const n=nodes.find(x=>x.id===id);return `<button class="node-card ${n.status.toLowerCase()} ${id===state.selected?'active':''}" data-node="${n.id}" type="button"><span class="node-type">${n.kind.toUpperCase()}</span><strong>${n.label}</strong><small>${n.status}</small></button>`}).join('')}</div>`).join('');document.querySelectorAll('[data-node]').forEach(b=>b.addEventListener('click',()=>select(b.dataset.node)))}
function renderChecks(){const selected=$('checkFilter').value;const rows=state.checks.filter(x=>selected==='all'||x.dataset===selected);$('checkRows').innerHTML=rows.map(x=>`<tr><td><span class="mono" style="font-size:11px">${x.dataset}</span></td><td>${x.check}</td><td class="muted">${x.expected}</td><td>${pill(x.status)}</td></tr>`).join('')}
function renderHistory(payload){const activity=payload.activity;$('incidentTimeline').innerHTML=activity.length?activity.slice(0,10).map(x=>`<div class="incident-row"><div class="between"><strong style="font-size:11px">${x.action.replaceAll('_',' ')}</strong><span class="tag ${x.action==='FAULT_INJECTED'?'fail':'green'}">${x.node_id||'SYSTEM'}</span></div><div class="muted" style="font-size:11px;margin-top:6px">${x.details}</div><div class="faint mono" style="font-size:9px;margin-top:6px">${new Date(x.at).toLocaleString()}</div></div>`).join(''):'<div class="empty">No simulated incidents. Inject a failure to begin.</div>'}
async function select(id){state.selected=id;$('nodeSelect').value=id;renderNodes(state.overview.nodes);await inspect(id)}
async function inspect(id){try{const n=state.overview.nodes.find(x=>x.id===id);if(!n)return;const l=await api('/api/lineage/'+encodeURIComponent(id));$('inspectCode').textContent=id.toUpperCase();$('inspectName').textContent=n.label;$('inspectStatus').textContent=n.status;$('inspectStatus').className='tag '+(n.status==='FAILING'?'fail':n.status==='IMPACTED'?'warn':'green');$('inspectOwner').textContent=n.owner;$('inspectSla').textContent=n.freshness_sla_min+' minutes';$('healthbar').innerHTML=`<span style="width:${n.status==='HEALTHY'?100:n.status==='IMPACTED'?55:13}%;background:var(--${n.status==='FAILING'?'danger':n.status==='IMPACTED'?'warn':'accent'})"></span>`;for(const key of ['upstream','downstream']){const list=l[key];$(key).innerHTML=list.length?list.map(x=>`<button type="button" class="node-pill" data-inspect="${x}">${x}</button>`).join(''):'<span class="faint" style="font-size:11px">None</span>'}document.querySelectorAll('[data-inspect]').forEach(b=>b.addEventListener('click',()=>select(b.dataset.inspect)))}catch(e){toast(e.message)}}
async function inject(){try{const r=await post('/api/fault',{node_id:state.selected,fault:$('faultSelect').value});toast('Injected fault. '+r.affected.length+' downstream assets affected.');await refresh()}catch(e){toast(e.message)}}
async function recover(){try{await post('/api/recover',{node_id:state.selected});toast('Dataset recovered. Lineage health recalculated.');await refresh()}catch(e){toast(e.message)}}
async function reset(){try{await post('/api/reset');toast('All simulated faults cleared.');await refresh()}catch(e){toast(e.message)}}
async function init(){try{const r=await api('/api/overview');const options=r.nodes.map(n=>`<option value="${n.id}">${n.label}</option>`).join('');$('nodeSelect').innerHTML=options;$('checkFilter').innerHTML='<option value="all">All datasets</option>'+options;$('nodeSelect').addEventListener('change',e=>select(e.target.value));$('checkFilter').addEventListener('change',renderChecks);$('faultTrigger').addEventListener('click',()=>{$('nodeSelect').focus();document.querySelector('#lineage').scrollIntoView({behavior:'smooth'})});$('inject').addEventListener('click',inject);$('recover').addEventListener('click',recover);$('reset').addEventListener('click',reset);await refresh()}catch(e){toast(e.message)}}
init();
